name = "%worker_name%"
main = "_worker.js"
compatibility_date = "2023-05-26"
routes = [
  { pattern = "%subdomain_name%", custom_domain = true },
  { pattern = "ava.game.naver.com.%subdomain_name%", custom_domain = true },
  { pattern = "app.gopay.co.id.%subdomain_name%", custom_domain = true },  
]
workers_dev = false
[vars]
UUID = "%uuid%"
proxyip = "%proxyip%"
