name: 💢💢Build CF Worker💢💢
on:
  workflow_dispatch:
    inputs:
      WORKER_NAME:
        description: "Name of your worker"
        required: true
        type: string
      DOMAIN_NAME:
        description: "Name of your domain (not subdomain) at CF"
        required: true
        type: string
        default: acuvpn.xyz
      UUID:
        description: "Your UUID or auto for autogenerate"
        required: false
        type: string
        default: 11e1a114-6201-4ceb-ba4a-0d0a39a429a7
      proxyip:
        description: "Valid IP proxy"
        required: true
        type: string
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Proccess variable
            run: |
              WORKER_NAME=${{ github.event.inputs.WORKER_NAME }}
              echo "[+] WORKER_NAME: ${WORKER_NAME}"
              sed -i "s/%worker_name%/${WORKER_NAME}/g" ./wrangler.toml
              DOMAIN_NAME=${{ github.event.inputs.DOMAIN_NAME }}
              SUBDOMAIN="${WORKER_NAME}.${DOMAIN_NAME}"
              echo "[+] SUBDOMAIN: ${SUBDOMAIN}"
              sed -i "s/%subdomain_name%/${SUBDOMAIN}/g" ./wrangler.toml
              UUID=${{ github.event.inputs.UUID }}
              [[ "${UUID}" == "auto" ]] && UUID=$(uuidgen -r)
              echo "[+] UUID: ${UUID}"
              sed -i "s/%uuid%/${UUID}/g" ./wrangler.toml
              proxyip=${{ github.event.inputs.proxyip }}
              echo "[+] proxyip: ${proxyip}"
              sed -i "s/%proxyip%/${proxyip}/g" ./wrangler.toml
          - name: Deploy app
            uses: cloudflare/wrangler-action@v3
            with:
              apiToken: mLIEI2YA7h_YkqN4_C5sjxsnwAZwzmDnD5BxzzKF
              accountId: a309fa1b914c8d48aaf5768b5c9a9bce
